/* PENDING PO ONLINE v5 — tanpa service/secret key di browser. */
'use strict';
const $ = id => document.getElementById(id);
const CONFIG = window.PENDING_PO_CONFIG || {};
const configured = /^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(CONFIG.url || '')
  && /^sb_publishable_[a-zA-Z0-9_-]+$/.test(CONFIG.publishableKey || '');
let sb = null, user = null, me = null, state = emptyState(), realtime = null, refreshTimer = null, reloadTimer = null;
let reloadBusy = false, reloadAgain = false, currentPage = 'dashboard', modalEditingPO = null, modalEditingShipment = null;
const tables = ['sales','item_types','expeditions','profiles','purchase_orders','po_items','shipments','shipment_items'];
function emptyState(){return {sales:[],item_types:[],expeditions:[],profiles:[],purchase_orders:[],po_items:[],shipments:[],shipment_items:[]}}
function esc(x){return String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(x){return Number(x||0).toLocaleString('id-ID')}
function today(){let d=new Date(), local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
function alertToast(text, bad=false){const n=$('toast');n.textContent=text;n.style.background=bad?'#991b1b':'#13243e';n.style.display='block';clearTimeout(n._timer);n._timer=setTimeout(()=>n.style.display='none',6500)}
function errorText(e){if(!e)return 'Terjadi kesalahan';let t=String(e.message||e);if(/duplicate key|unique constraint/i.test(t))return 'Data sudah ada / nomor PO sudah digunakan.';if(/foreign key|violates foreign/i.test(t))return 'Data masih digunakan oleh PO / pengiriman / akun.';return t}
function setSync(t, bad=false){$('syncStatus').textContent=t;$('syncStatus').style.background=bad?'#fee2e2':'#eaf2ff';$('syncStatus').style.color=bad?'#991b1b':'#1d4ed8'}
function admin(){return me?.role==='admin'}
function named(table,id){return state[table].find(x=>x.id===id)?.name || '—'}
function ownPO(p){return admin() || (p.created_by===user?.id && me?.sales_id && p.sales_id===me.sales_id)}
function pos(){return state.purchase_orders.slice().sort((a,b)=>b.po_date.localeCompare(a.po_date)||b.created_at.localeCompare(a.created_at))}
function items(po){return state.po_items.filter(x=>x.po_id===po.id)}
function shipmentItems(ship){return state.shipment_items.filter(x=>x.shipment_id===ship.id)}
function shippedQty(lineId, ignoreShipment=null){return state.shipment_items.filter(si=>si.po_item_id===lineId && (!ignoreShipment || si.shipment_id!==ignoreShipment)).reduce((a,x)=>a+Number(x.qty),0)}
function summary(po){const lines=items(po);const qty=lines.reduce((a,x)=>a+x.qty,0);const sent=lines.reduce((a,x)=>a+shippedQty(x.id),0);return {qty,sent,pending:Math.max(0,qty-sent)}}
function totals(){return pos().reduce((s,p)=>{let x=summary(p);s.qty+=x.qty;s.sent+=x.sent;s.pending+=x.pending;return s},{qty:0,sent:0,pending:0})}
function options(rows,selected,placeholder='-- Pilih --'){return `<option value="">${esc(placeholder)}</option>`+rows.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x.name)}</option>`).join('')}
function poOptions(selected){return pos().map(p=>`<option value="${esc(p.id)}" ${selected===p.id?'selected':''}>${esc(p.po_no)} — ${esc(p.store)}</option>`).join('')}
function table(headers,rows){return `<table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows || `<tr><td colspan="${headers.length}" class="dim">Belum ada data.</td></tr>`}</tbody></table>`}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.add('on')}
function closeModal(){$('modal').classList.remove('on');$('modalBody').innerHTML='';modalEditingPO=null;modalEditingShipment=null}
function clearConnection(){if(realtime && sb)sb.removeChannel(realtime);realtime=null;if(refreshTimer)clearInterval(refreshTimer);refreshTimer=null;if(reloadTimer)clearTimeout(reloadTimer);reloadTimer=null}
function signedOut(){clearConnection();user=null;me=null;state=emptyState();$('app').classList.add('hidden');$('authPage').classList.remove('hidden');$('password').value='';setSync('Terputus')}
async function handleAuth(){if(!sb)return;const {data:{user:found},error}=await sb.auth.getUser();if(error||!found){signedOut();return}user=found;await loadEverything(true)}
async function loadEverything(first=false){if(!user)return;if(reloadBusy){reloadAgain=true;return}reloadBusy=true;setSync('Menyinkronkan...');try{
 const profile=await sb.from('profiles').select('id,email,display_name,role,sales_id').eq('id',user.id).single();if(profile.error)throw profile.error;if(!profile.data)throw Error('Profil akun belum tersedia. Jalankan SQL database.sql.');me=profile.data;
 const results=await Promise.all(tables.map(async name=>{let q=sb.from(name).select('*');let {data,error}=await q;if(error)throw Error(name+': '+error.message);return [name,data||[]]}));const next=emptyState();for(const [name,data] of results)next[name]=data;state=next;
 $('userTag').textContent=(me.display_name||me.email)+' • '+(admin()?'Admin':'Sales');document.querySelectorAll('[data-admin]').forEach(el=>el.classList.toggle('hidden',!admin()));if(!admin() && ['ship','master'].includes(currentPage))currentPage='dashboard';$('authPage').classList.add('hidden');$('app').classList.remove('hidden');render();setSync('✓ Tersinkron '+new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}));
 if(first){startRealtime();if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(document.visibilityState==='visible')loadEverything()},45000)}
 }catch(e){setSync('Gagal sinkron',true);alertToast(errorText(e),true);if(first && !me){signedOut();$('authMessage').textContent='Gagal membuka database: '+errorText(e)}}finally{reloadBusy=false;if(reloadAgain){reloadAgain=false;loadEverything()}}}
function startRealtime(){if(realtime)sb.removeChannel(realtime);realtime=sb.channel('pending-po-live');tables.forEach(t=>realtime.on('postgres_changes',{event:'*',schema:'public',table:t},()=>{clearTimeout(reloadTimer);reloadTimer=setTimeout(()=>loadEverything(),500)}));realtime.subscribe(s=>{if(s==='CHANNEL_ERROR'||s==='TIMED_OUT')setSync('Realtime terputus — refresh otomatis',true)})}
function goPage(id){if(!admin() && ['ship','master'].includes(id))return;currentPage=id;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('#navigation button').forEach(x=>x.classList.toggle('on',x.dataset.page===id));render()}
function render(){if(!me)return;const t=totals();$('dpo').textContent=fmt(state.purchase_orders.length);$('dqty').textContent=fmt(t.qty);$('dship').textContent=fmt(t.sent);$('dpend').textContent=fmt(t.pending);$('dashboardHint').textContent=admin()?'Admin: melihat seluruh PO dan dapat mencatat pengiriman.':'Sales: melihat PO yang dibuat sendiri atau ditugaskan ke nama Sales Anda. Pengiriman dicatat Admin.';renderPO();renderShip();renderPending();renderDetail();renderReport();if(admin())renderMasters()}
function renderPO(){let search=$('poSearch').value.trim().toLowerCase();let list=pos().filter(p=>(p.po_no+' '+p.store+' '+named('sales',p.sales_id)).toLowerCase().includes(search));let rows=list.map(p=>{let s=summary(p);return `<tr><td><b>${esc(p.po_no)}</b></td><td>${esc(p.po_date)}</td><td>${esc(p.store)}</td><td>${esc(named('sales',p.sales_id))}</td><td>${fmt(s.qty)}</td><td><b>${fmt(s.pending)}</b></td><td><span class="pill ${s.pending===0?'done':''}">${s.pending===0?'Selesai':'Pending'}</span></td><td>${ownPO(p)?`<button class="iconbtn no-print" data-edit-po="${p.id}">Edit</button>`:''}${admin()?`<button class="iconbtn no-print" style="color:#b91c1c" data-delete-po="${p.id}">Hapus</button>`:''}</td></tr>`}).join('');$('poList').innerHTML=table(['No PO','Tanggal','Toko','Sales','Qty PO','Pending','Status','Aksi'],rows)}
function renderShip(){if(!admin())return;let rows=state.shipments.slice().sort((a,b)=>b.ship_date.localeCompare(a.ship_date)).map(s=>{let p=state.purchase_orders.find(p=>p.id===s.po_id);return `<tr><td>${esc(p?.po_no||'—')}</td><td>${esc(s.ship_date)}</td><td>${esc(p?.store||'—')}</td><td>${shipmentItems(s).map(i=>esc(named('item_types',state.po_items.find(l=>l.id===i.po_item_id)?.type_id))).join('<br>')}</td><td>${shipmentItems(s).map(i=>fmt(i.qty)).join('<br>')}</td><td>${esc(named('expeditions',s.expedition_id))}</td><td><button class="iconbtn" data-edit-ship="${s.id}">Edit</button><button class="iconbtn" style="color:#b91c1c" data-delete-ship="${s.id}">Hapus</button></td></tr>`}).join('');$('shipList').innerHTML=table(['No PO','Tanggal','Toko','Barang','Qty','Ekspedisi','Aksi'],rows)}
function pendingRows(){return pos().flatMap(p=>items(p).map(i=>({po:p,line:i,sent:shippedQty(i.id),remaining:Math.max(0,i.qty-shippedQty(i.id))}))).filter(r=>r.remaining>0)}
function renderPending(){let rows=pendingRows().map(r=>`<tr><td>${esc(r.po.po_no)}</td><td>${esc(r.po.store)}</td><td>${esc(named('sales',r.po.sales_id))}</td><td>${esc(named('item_types',r.line.type_id))}</td><td>${fmt(r.line.qty)}</td><td>${fmt(r.sent)}</td><td><b>${fmt(r.remaining)}</b></td></tr>`).join('');$('pendingList').innerHTML=table(['No PO','Toko','Sales','Type Barang','Qty PO','Terkirim','Pending'],rows)}
function renderDetail(){const old=$('detailSel').value;$('detailSel').innerHTML=poOptions(old);if(!state.purchase_orders.some(p=>p.id===old) && pos()[0])$('detailSel').value=pos()[0].id;const p=state.purchase_orders.find(x=>x.id===$('detailSel').value);if(!p){$('detailContent').innerHTML='<p class="dim">Belum ada PO.</p>';return}let s=summary(p);const rows=items(p).map(i=>`<tr><td>${esc(named('item_types',i.type_id))}</td><td>${fmt(i.qty)}</td><td>${fmt(shippedQty(i.id))}</td><td><b>${fmt(Math.max(0,i.qty-shippedQty(i.id)))}</b></td></tr>`).join('');const deliveries=state.shipments.filter(x=>x.po_id===p.id).map(sh=>`<tr><td>${esc(sh.ship_date)}</td><td>${esc(named('expeditions',sh.expedition_id))}</td><td>${shipmentItems(sh).map(i=>esc(named('item_types',state.po_items.find(l=>l.id===i.po_item_id)?.type_id))+': '+fmt(i.qty)).join('<br>')}</td></tr>`).join('');$('detailContent').innerHTML=`<p><b>${esc(p.po_no)}</b> · ${esc(p.store)} · Sales: ${esc(named('sales',p.sales_id))}</p><div class="cards"><div class="card">Qty PO<div class="value">${fmt(s.qty)}</div></div><div class="card">Terkirim<div class="value">${fmt(s.sent)}</div></div><div class="card">Pending<div class="value">${fmt(s.pending)}</div></div></div><h3>Rincian barang</h3>${table(['Type','Qty PO','Terkirim','Pending'],rows)}<h3>Riwayat pengiriman</h3>${table(['Tanggal','Ekspedisi','Barang / Qty'],deliveries)}`}
function renderReport(){const t=totals();$('reportContent').innerHTML=`<p class="dim">Tanggal cetak: ${esc(today())} · ${admin()?'Semua PO':'PO dalam akses akun Sales'}</p><div class="reportline">Jumlah PO: <b>${fmt(state.purchase_orders.length)}</b></div><div class="reportline">Total Qty PO: <b>${fmt(t.qty)}</b></div><div class="reportline">Total Qty terkirim: <b>${fmt(t.sent)}</b></div><div class="reportline">Total Qty pending: <b>${fmt(t.pending)}</b></div><h3>Rincian per PO</h3>${table(['No PO','Tanggal','Toko','Sales','Qty PO','Terkirim','Pending'],pos().map(p=>{let s=summary(p);return `<tr><td>${esc(p.po_no)}</td><td>${esc(p.po_date)}</td><td>${esc(p.store)}</td><td>${esc(named('sales',p.sales_id))}</td><td>${fmt(s.qty)}</td><td>${fmt(s.sent)}</td><td>${fmt(s.pending)}</td></tr>`}).join(''))}`}
function renderMasters(){for(const [tbl,id] of [['sales','salesList'],['item_types','typesList'],['expeditions','expList']]){$(id).innerHTML=state[tbl].map(x=>`<div class="mutelist"><span>${esc(x.name)}</span><button class="danger" data-master-delete="${tbl}" data-id="${x.id}">Hapus</button></div>`).join('')||'<p class="dim">Belum ada data.</p>'}let salesOpts=options(state.sales,null,'Belum ditautkan');$('profileList').innerHTML=state.profiles.map(p=>`<div class="mutelist" style="display:block"><b>${esc(p.display_name||p.email)}</b><div class="dim">${esc(p.email)} · ${esc(p.role)}</div>${p.role==='sales'?`<label>Tautkan akun ke Sales</label><select data-profile-sales="${p.id}">${options(state.sales,p.sales_id,'Belum ditautkan')}</select>`:''}</div>`).join('')||'<p class="dim">Belum ada akun.</p>'}
function poLine(typeId='',qty=''){return `<div class="itemrow"><select class="po-type" required>${options(state.item_types,typeId,'Pilih type barang')}</select><input class="po-qty" type="number" min="1" step="1" required placeholder="Qty" value="${esc(qty)}"><button class="danger remove-line" type="button" title="Hapus baris">×</button></div>`}
function showPO(id=null){let p=id?state.purchase_orders.find(x=>x.id===id):null;if(p && !ownPO(p)){alertToast('Tidak memiliki izin mengubah PO ini.',true);return}if(!state.sales.length||!state.item_types.length){alertToast('Admin harus menambahkan Sales dan Type Barang terlebih dahulu.',true);return}if(!admin()&&!me.sales_id){alertToast('Akun belum ditautkan ke nama Sales. Hubungi Admin.',true);return}modalEditingPO=id;
 let salesChoice=p?.sales_id||(admin()?state.sales[0].id:me.sales_id);let salesRows=admin()?state.sales:state.sales.filter(x=>x.id===me.sales_id);let poLines=p?items(p).map(i=>poLine(i.type_id,i.qty)).join(''):poLine();
 openModal(p?'Edit PO':'Tambah PO',`<form id="poForm"><div class="grid2"><div><label>No PO</label><input name="po_no" required maxlength="100" value="${esc(p?.po_no||'')}" placeholder="PO-001"></div><div><label>Tanggal</label><input name="po_date" type="date" required value="${esc(p?.po_date||today())}"></div><div><label>Nama Toko (ketik langsung)</label><input name="store" required maxlength="150" value="${esc(p?.store||'')}" placeholder="Nama toko"></div><div><label>Sales</label><select name="sales_id" required>${options(salesRows,salesChoice,'Pilih sales')}</select></div></div><h3>Barang dalam PO</h3><div id="poLines">${poLines}</div><div class="btnrow"><button type="button" class="secondary" id="addLine">＋ Tambah Barang</button></div><div class="notice warn">Jika barang sudah pernah dikirim, type barang tidak bisa dihapus dan Qty tidak bisa dikurangi di bawah jumlah terkirim.</div><div class="btnrow"><button type="submit" class="primary">Simpan PO</button><button type="button" class="secondary" id="cancelForm">Batal</button></div></form>`)}
async function submitPO(form){const fd=new FormData(form);let parts=[...$('poLines').querySelectorAll('.itemrow')].map(r=>({type_id:r.querySelector('.po-type').value,qty:Number(r.querySelector('.po-qty').value)}));if(!parts.length||parts.some(x=>!x.type_id||!Number.isSafeInteger(x.qty)||x.qty<=0))throw Error('Isi minimal satu Type Barang dan Qty positif.');if(new Set(parts.map(x=>x.type_id)).size!==parts.length)throw Error('Type Barang tidak boleh sama dalam satu PO.');let {error}=await sb.rpc('save_po',{p_id:modalEditingPO,p_no:fd.get('po_no').trim(),p_date:fd.get('po_date'),p_store:fd.get('store').trim(),p_sales:fd.get('sales_id'),p_items:parts});if(error)throw error;closeModal();await loadEverything();alertToast('PO berhasil disimpan ke cloud.')}
function shipLine(line,qty=''){const rem=Math.max(0,line.qty-shippedQty(line.id,modalEditingShipment));return `<div class="itemrow" data-line="${line.id}"><span>${esc(named('item_types',line.type_id))}<br><small>Sisa yang dapat dikirim: ${fmt(rem)}</small></span><input type="number" class="shipqty" min="0" max="${rem}" step="1" value="${esc(qty)}" placeholder="Qty" aria-label="Qty kirim ${esc(named('item_types',line.type_id))}"><span class="dim">pcs</span></div>`}
function showShipment(id=null){if(!admin())return;if(!pos().length||!state.expeditions.length){alertToast('Buat PO dan tambahkan Ekspedisi terlebih dahulu.',true);return}let ship=id?state.shipments.find(s=>s.id===id):null;modalEditingShipment=id;let poId=ship?.po_id||pos()[0].id;let p=state.purchase_orders.find(p=>p.id===poId);let oldMap=new Map(ship?shipmentItems(ship).map(si=>[si.po_item_id,si.qty]):[]);openModal(ship?'Edit Pengiriman':'Tambah Pengiriman',`<form id="shipForm"><label>PO</label><select name="po_id" id="shipPo" ${ship?'disabled':''} required>${poOptions(poId)}</select><div class="grid2"><div><label>Tanggal Kirim</label><input type="date" name="ship_date" value="${esc(ship?.ship_date||today())}" required></div><div><label>Ekspedisi</label><select name="expedition_id" required>${options(state.expeditions,ship?.expedition_id||state.expeditions[0].id)}</select></div></div><h3>Qty Pengiriman per Barang</h3><div id="shipLines">${items(p).map(i=>shipLine(i,oldMap.get(i.id)||'')).join('')}</div><div class="notice">Total pengiriman tiap barang tidak boleh melebihi Qty PO. Server juga memvalidasinya.</div><div class="btnrow"><button type="submit" class="primary">Simpan Pengiriman</button><button type="button" class="secondary" id="cancelForm">Batal</button></div></form>`)}
function refreshShipLines(poId){let p=state.purchase_orders.find(x=>x.id===poId);$('shipLines').innerHTML=p?items(p).map(i=>shipLine(i)).join(''):''}
async function submitShipment(form){if(!admin())throw Error('Hanya Admin yang boleh mencatat pengiriman.');let fd=new FormData(form);let poId=modalEditingShipment?state.shipments.find(s=>s.id===modalEditingShipment)?.po_id:fd.get('po_id');let parts=[...$('shipLines').querySelectorAll('.itemrow')].map(r=>({po_item_id:r.dataset.line,qty:Number(r.querySelector('.shipqty').value||0)}));if(parts.some(x=>!Number.isSafeInteger(x.qty)||x.qty<0))throw Error('Qty harus bilangan bulat non-negatif.');parts=parts.filter(x=>x.qty>0);if(!parts.length)throw Error('Isi minimal satu Qty pengiriman yang lebih dari 0.');let {error}=await sb.rpc('save_shipment',{p_id:modalEditingShipment,p_po:poId,p_date:fd.get('ship_date'),p_exp:fd.get('expedition_id'),p_items:parts});if(error)throw error;closeModal();await loadEverything();alertToast('Pengiriman tersimpan. Pending diperbarui.')}
async function deletePO(id){if(!admin())return;const p=state.purchase_orders.find(x=>x.id===id);if(!p||!confirm(`Hapus PO ${p.po_no} termasuk seluruh pengirimannya? Tindakan ini tidak dapat dibatalkan.`))return;const {error}=await sb.rpc('delete_po',{p_id:id});if(error)throw error;await loadEverything();alertToast('PO berhasil dihapus.')}
async function deleteShipment(id){if(!admin())return;if(!confirm('Hapus pengiriman ini? Qty pending akan dihitung ulang.'))return;let {error}=await sb.from('shipments').delete().eq('id',id);if(error)throw error;await loadEverything();alertToast('Pengiriman berhasil dihapus.')}
async function addMaster(form){if(!admin())return;let tbl=form.dataset.master;let name=form.elements.name.value.trim();if(!name)throw Error('Nama tidak boleh kosong.');const {error}=await sb.from(tbl).insert({name});if(error)throw error;form.reset();await loadEverything();alertToast('Data master berhasil ditambah.')}
async function delMaster(tbl,id){if(!admin()||!['sales','item_types','expeditions'].includes(tbl)||!confirm('Hapus data master ini? Data yang sedang digunakan tidak dapat dihapus.'))return;let {error}=await sb.from(tbl).delete().eq('id',id);if(error)throw error;await loadEverything();alertToast('Data master dihapus.')}
async function assignSales(profileId,salesId){if(!admin())return;let {error}=await sb.from('profiles').update({sales_id:salesId||null}).eq('id',profileId);if(error)throw error;await loadEverything();alertToast('Hak akses akun Sales diperbarui.')}
function downloadCSV(name,headers,rows){let csv='\ufeff'+[headers,...rows].map(line=>line.map(x=>'"'+String(x??'').replace(/"/g,'""').replace(/^[=+@\-\t\r]/,m=>"'"+m)+'"').join(',')).join('\r\n');let link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function exportPending(){downloadCSV('Pending_PO_'+today()+'.csv',['No PO','Tanggal PO','Toko','Sales','Type Barang','Qty PO','Terkirim','Pending'],pendingRows().map(r=>[r.po.po_no,r.po.po_date,r.po.store,named('sales',r.po.sales_id),named('item_types',r.line.type_id),r.line.qty,r.sent,r.remaining]))}
function exportReport(){downloadCSV('Laporan_PO_'+today()+'.csv',['No PO','Tanggal','Toko','Sales','Qty PO','Terkirim','Pending'],pos().map(p=>{let s=summary(p);return [p.po_no,p.po_date,p.store,named('sales',p.sales_id),s.qty,s.sent,s.pending]}))}
async function safeCall(fn){try{await fn()}catch(e){alertToast(errorText(e),true)}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const btn=$('loginBtn');btn.disabled=true;$('authMessage').textContent='Sedang login...';try{const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;await handleAuth();$('authMessage').textContent=''}catch(error){$('authMessage').textContent='Login gagal: '+errorText(error)}finally{btn.disabled=false}});
$('logoutBtn').addEventListener('click',()=>safeCall(async()=>{const {error}=await sb.auth.signOut();if(error)throw error;signedOut()}));
$('navigation').addEventListener('click',e=>{let b=e.target.closest('[data-page]');if(b)goPage(b.dataset.page)});
document.querySelectorAll('[data-refresh]').forEach(b=>b.addEventListener('click',()=>loadEverything()));
$('poSearch').addEventListener('input',renderPO);$('detailSel').addEventListener('change',renderDetail);
$('addPO').addEventListener('click',()=>showPO());$('addShip').addEventListener('click',()=>showShipment());
$('poList').addEventListener('click',e=>{let b=e.target.closest('[data-edit-po]');if(b)showPO(b.dataset.editPo);b=e.target.closest('[data-delete-po]');if(b)safeCall(()=>deletePO(b.dataset.deletePo))});
$('shipList').addEventListener('click',e=>{let b=e.target.closest('[data-edit-ship]');if(b)showShipment(b.dataset.editShip);b=e.target.closest('[data-delete-ship]');if(b)safeCall(()=>deleteShipment(b.dataset.deleteShip))});
$('closeModal').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});
$('modalBody').addEventListener('click',e=>{if(e.target.id==='addLine')$('poLines').insertAdjacentHTML('beforeend',poLine());if(e.target.closest('.remove-line'))e.target.closest('.itemrow').remove();if(e.target.id==='cancelForm')closeModal()});
$('modalBody').addEventListener('change',e=>{if(e.target.id==='shipPo')refreshShipLines(e.target.value)});
$('modalBody').addEventListener('submit',e=>{e.preventDefault();const form=e.target;const button=form.querySelector('[type=submit]');button.disabled=true;safeCall(async()=>{try{if(form.id==='poForm')await submitPO(form);else if(form.id==='shipForm')await submitShipment(form)}finally{button.disabled=false}})});
document.querySelectorAll('[data-master]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();safeCall(()=>addMaster(form))}));
$('master').addEventListener('click',e=>{let b=e.target.closest('[data-master-delete]');if(b)safeCall(()=>delMaster(b.dataset.masterDelete,b.dataset.id))});
$('master').addEventListener('change',e=>{let s=e.target.closest('[data-profile-sales]');if(s)safeCall(()=>assignSales(s.dataset.profileSales,s.value))});
$('exportPending').addEventListener('click',exportPending);$('exportReport').addEventListener('click',exportReport);$('printReport').addEventListener('click',()=>window.print());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&user)loadEverything()});
if(configured && window.supabase?.createClient){sb=window.supabase.createClient(CONFIG.url.replace(/\/$/,''),CONFIG.publishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});sb.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')queueMicrotask(signedOut);if(event==='SIGNED_IN'&&(!user||user.id===undefined))queueMicrotask(()=>handleAuth())});handleAuth()}
else{$('configNotice').classList.remove('hidden');$('loginBtn').disabled=true;$('authMessage').textContent=!window.supabase?'Library Supabase gagal dimuat. Periksa koneksi internet.':'Isi config.js untuk menghubungkan aplikasi ke Supabase.'}
